version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vscode_dev_container_app
    ports:
      - 4000:4000
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2-alpine
    container_name: vscode_dev_container_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: password
